language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3
    - otp_release: 19.3
      elixir: 1.3
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
    - otp_release: 20.0
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.6
    - otp_release: 20.0
      elixir: 1.7
    - otp_release: 21.0
      elixir: 1.7
    - otp_release: 22.0
      elixir: 1.7
    - otp_release: 20.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.8
    - otp_release: 22.0
      elixir: 1.8
    - otp_release: 20.0
      elixir: 1.9
    - otp_release: 21.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.9
sudo: false
after_script:
  - MIX_ENV=test mix coveralls.travis
  - mix credo
